### ISSUE TITLE
Tool has been broken by a recent API change

### ISSUE THREAD

**Issue by AT2025** [HenryBalassiano/reddit-search-tool#25] opened 2023-01-05 23:59 UTC
About a month ago the tool stopped working and only now have I found out there's been a major API change. I'm not sure if this project has been maintained since its inception but it is worth looking at, especially because your frontend is much nicer to use than others.

**Comment by AT2025** [comment] 2023-02-27 18:53
Ingest of old submissions from 2006 and beyond has begun. No email back from the dev since contacting him in December. Perhaps someone else following this project can whip up their own interface or update his old one, though I'm not sure how that'd work since he's not approving any pulls either. I've not been able to reach him through any manner, public or otherwise.

I've stopped short of contacting him through his employer's employee email address as that would be a flagrant ethics and privacy issue. If any of you find Henry on social media such as the grams, drop him a question. This may have been a project but it was a good one.

**Comment by HenryBalassiano** [comment] 2023-04-10 04:26
The issue is now fixed everyone, thank you so much for all of your support!

**Comment by HenryBalassiano** [comment] 2023-04-10 04:26
The issue is now fixed everyone, thank you so much for all of your support!

**Closed** 2023-04-10 04:26 UTC
